#!/bin/bash
# Test script cho WHO command

echo "=== Test đăng nhập với các status khác nhau ==="
echo ""
echo "Tài khoản test:"
echo "1. hungng / hung2a9 (status=1, active) - Nên đăng nhập được"
echo "2. namnk / namnk123 (status=0, blocked) - Nên bị từ chối"
echo "3. admin / admin123 (status=0, blocked) - Nên bị từ chối"
echo ""
echo "Hướng dẫn test:"
echo "1. Chạy: ./server 8080"
echo "2. Ở terminal khác, chạy: ./client 127.0.0.1 8080"
echo ""
echo "Test case 1: Đăng nhập thành công (hungng)"
echo "  - Nhập: hungng"
echo "  - Nhập: hung2a9"
echo "  - Kết quả mong đợi: [CLIENT] Server CONFIRM (0x11): hungng"
echo ""
echo "Test case 2: Tài khoản bị khóa (namnk)"
echo "  - Nhập: namnk"
echo "  - Nhập: namnk123"
echo "  - Kết quả mong đợi: [CLIENT] Server DENY (0x00): ERROR: Account is blocked."
echo ""
echo "Test case 3: WHO command"
echo "  - Sau khi đăng nhập thành công"
echo "  - Nhập: who"
echo "  - Kết quả mong đợi: [CLIENT] Logged-in users: hungng"
echo ""
echo "Test case 4: Multiple clients + WHO"
echo "  - Terminal 1: hungng đăng nhập"
echo "  - Terminal 2: quangvn đăng nhập"
echo "  - Từ bất kỳ terminal nào: who"
echo "  - Kết quả mong đợi: [CLIENT] Logged-in users: hungng, quangvn"
echo ""
